### ISSUE TITLE
Error al hacer makefile

### ISSUE THREAD

**Issue by guillem9988** [DarkJaslo/Horaris-FIB#1]
Sabes pq me da este error al hacer make? Tampoco me deja hacer qmake
![imatge](https://github.com/user-attachments/assets/f3762ddd-12fb-4dde-9042-10c4f67130b4)

**Comment by DarkJaslo** [comment]
Me hace pensar que no tienes qmake instalado. Si lo has usado antes y te funciona con otros proyectos, entonces me temo que no sé de qué se trata. Si no, prueba con `sudo apt install qt5-qmake qtbase5-dev` (te añado qt5 también por si las moscas).

Si te sirve, eso sí, hay una branch muy reciente en el repositorio (switch-to-cmake) donde estoy añadiendo soporte para compilar con CMake, que suele ser mucho más compatible en general con todo. De momento me funciona, prueba a bajártela, y desde el directorio del repo,

Si no tienes `cmake` instalado,  

`sudo apt install cmake`
`mkdir build`
`cd build`
`cmake ..`
Si no da errores (warnings verás seguro),
`make`

**Comment by DarkJaslo** [comment]
Y ya que son fechas de matrícula, si aún no lo tienes arreglado, con eso tampoco compila y quieres una mano con los horarios, me dices por aquí o me das algún contacto.

**Comment by guillem9988** [comment]
me da este error ahora
![image](https://github.com/user-attachments/assets/50a55e1d-f2c2-4362-bcc8-77e89cde9112)

**Comment by DarkJaslo** [comment]
Eso es seguramente porque no tienes la libreria SSL, prueba con:
`sudo apt install libssl-dev`

**Comment by guillem9988** [comment]
muchas gracias por todo, ya me deja
